name: Regression Tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install npm dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Archive visual regression failures
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: visual-regression-report
          path: tests/pages/__image_snapshots__/__diff_output__
